export const ENTER_NAME_SUCCESS = 'ENTER_NAME_SUCCESS';

export const ADD_MESSAGE = 'ADD_MESSAGE';
export const SEND_MESSAGE = 'SEND_MESSAGE';
export const MESSAGE_FIELD_UPDATE = 'MESSAGE_FIELD_UPDATE';