export const SET_HANDLE = 'SET_HANDLE';
export const HANDLE_UPDATE = 'HANDLE_UPDATE';

export const ADD_MESSAGE = 'ADD_MESSAGE';
export const SEND_MESSAGE = 'SEND_MESSAGE';

export const MESSAGE_FIELD_UPDATE = 'MESSAGE_FIELD_UPDATE';